# Generated by Django 4.2.4 on 2023-08-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_login_id_alter_user_username_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
