# Generated by Django 4.2.4 on 2023-08-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_login_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='test@example.com', max_length=150),
        ),
    ]
