# Generated by Django 4.2.4 on 2023-09-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="deleted_img",
            field=models.CharField(blank=True, null=True),
        ),
    ]
