# Generated by Django 4.2.4 on 2023-09-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_post_deleted_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="deleted_img",
            field=models.URLField(blank=True, null=True),
        ),
    ]
