# Generated by Django 4.2.4 on 2023-09-03 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_post_deleted_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="deleted_img",
        ),
    ]
