# Generated by Django 4.2.4 on 2023-09-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.CharField(blank=True, null=True),
        ),
    ]
