# Generated by Django 4.2.4 on 2023-09-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.TextField(blank=True, null=True),
        ),
    ]
