# Generated by Django 4.2.4 on 2023-09-01 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_profile_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profile_img",
            new_name="image_url",
        ),
    ]
