# Generated by Django 4.2.4 on 2023-09-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_user_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image_url",
            field=models.CharField(blank=True, null=True),
        ),
    ]
